source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Eyshen/ios-zy-framework-cocoapods-specs.git'
platform :ios, '7.0'

target :'ZYCommon-master' do

#pod 'ZYUIRoutable/API'
#pod 'KVOController'
pod 'ZYLoggingCocoaLumberjack'
pod 'Masonry','~> 1.0'
pod 'Reachability', '3.2'
pod 'ZYConfig'
pod 'ZYLoggingAPI'
pod 'ZYJSON'

end
